Repository wecode-bootcamp-korea/10-WannaOne-frontend, pull requests merged in 2020-08, with the labels that each got.

#2 [신영재] Add: 페이스북 소셜 로그인 기능 구현
  package-lock.json
  package.json
  public/images/ic-google.png
  public/images/ic-naver-white.png
  public/images/login-bg.png
  src/Config.js
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/LoginIcons.js
  src/Pages/Login/LoginInput.js
  src/Pages/Login/LoginInput.scss
  src/Pages/Login/LoginTitle.js
  src/Pages/Login/LoginTitle.scss
  src/Styles/common.scss
  src/Styles/reset.scss
Labels: Status: 리뷰 요청

#3 [배정규] Add: 회원가입 및 카카오 소셜로그인 1차 구현 완료
  package-lock.json
  package.json
  public/images/ic-google 2.png
  public/images/ic-naver-white 2.png
  public/index.html
  src/Config.js
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Pages/SignUp/SocialIcons.js
  src/Pages/SignUp/SocialLogin.js
  src/Pages/SignUp/SocialLogin.scss
Labels: Status: 리뷰 요청

#8 [이윤식] Add : 메인페이지 추가 (리팩토링,추가기능구현 진행중)
  package-lock.json
  package.json
  public/data/TitleSlide.json
  public/images/Profiling.webp
  public/images/img-signature-plus.png
  public/images/primary.webp
  public/images/profilemaster.webp
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/FooterIcon/FooterIcon.js
  src/Components/Footer/FooterIcon/FooterIcon.scss
  src/Components/Footer/FooterIcon/Icons/FacebookIcon.js
  src/Components/Footer/FooterIcon/Icons/FacebookIcon.scss
  src/Components/Footer/FooterIcon/Icons/InstagramIcon.js
  src/Components/Footer/FooterIcon/Icons/InstagramIcon.scss
  src/Components/Footer/FooterIcon/Icons/MobileIcon.js
  src/Components/Footer/FooterIcon/Icons/MobileIcon.scss
  src/Components/Footer/FooterIcon/Icons/NaverIcon.js
  src/Components/Footer/FooterIcon/Icons/NaverIcon.scss
  src/Components/Footer/FooterIcon/Icons/YoutubeIcon.js
  src/Components/Footer/FooterIcon/Icons/YoutubeIcon.scss
  src/Components/Footer/KakaoBtn/KakaoBtn.js
  src/Components/Footer/KakaoBtn/KakaoBtn.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Signature/Main/ClassAbout/ClassAbout.js
  src/Components/Signature/Main/ClassAbout/ClassAbout.scss
  src/Components/Signature/Main/ClassCardList/ClassCardList.js
  src/Components/Signature/Main/ClassCardList/ClassCardList.scss
  src/Components/Signature/Main/ClassCardList/OpenSignatureClass/OpenSignatureClass.js
  src/Components/Signature/Main/ClassCardList/OpenSignatureClass/OpenSignatureClass.scss
  src/Components/Signature/Main/ClassInfo/ClassInfo.js
  src/Components/Signature/Main/ClassInfo/ClassInfo.scss
  src/Components/Signature/Main/TitleSlide/SlideButton/ButtonIcon/ButtonIcon.js
  src/Components/Signature/Main/TitleSlide/SlideButton/SlideButton.js
  src/Components/Signature/Main/TitleSlide/SlideButton/SlideButton.scss
  src/Components/Signature/Main/TitleSlide/TitleSlide.js
  src/Components/Signature/Main/TitleSlide/TitleSlide.scss
  src/Config.js
  src/Pages/Signature/Main/Main.js
  src/Pages/Signature/Main/Main.scss
  src/Routes.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#4 [배정규] Add: 시그니처 상세페이지 사이드바 레이아웃 완료
  public/images/class101Logo.jpg
  src/Components/SignatureSideBar/Components/Class101IntroductionBanner.js
  src/Components/SignatureSideBar/Components/ClassApplyBtn.js
  src/Components/SignatureSideBar/Components/Label.js
  src/Components/SignatureSideBar/Components/ProductPriceInfo.js
  src/Components/SignatureSideBar/Components/SummaryOptions.js
  src/Components/SignatureSideBar/Components/SummaryOptions.scss
  src/Components/SignatureSideBar/Components/WishShare.js
  src/Components/SignatureSideBar/SignatureSideBar.js
  src/Config.js
  src/Routes.js
Labels: Status: 리뷰 요청

#9 [배정규] Add: MyPage LeftAside 레이아웃 완료
  public/data/MyPageData.json
  public/images/membership.png
  public/images/pointBall.png
  public/images/profileImg.png
  public/index.html
  src/Config.js
  src/Pages/MyPage/Components/Content/MyViewClassList/MyViewClassList.js
  src/Pages/MyPage/Components/Content/MyViewClassList/MyViewClassList.scss
  src/Pages/MyPage/Components/Content/MyViewClassList/ViewClass.js
  src/Pages/MyPage/Components/Content/MyViewClassList/ViewClass.scss
  src/Pages/MyPage/Components/Content/WishClassList/WishClass.js
  src/Pages/MyPage/Components/Content/WishClassList/WishClass.scss
  src/Pages/MyPage/Components/Content/WishClassList/WishClassList.js
  src/Pages/MyPage/Components/Content/WishClassList/WishClassList.scss
  src/Pages/MyPage/Components/LeftAside/MyAttendance/MyAttendance.js
  src/Pages/MyPage/Components/LeftAside/ProfileCard/Coupon.js
  src/Pages/MyPage/Components/LeftAside/ProfileCard/Order.js
  src/Pages/MyPage/Components/LeftAside/ProfileCard/Point.js
  src/Pages/MyPage/Components/LeftAside/ProfileCard/ProfileCard.js
  src/Pages/MyPage/Components/LeftAside/ProfileCard/ProfileEdit.js
  src/Pages/MyPage/Components/LeftAside/ProfileCard/Wish.js
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/FooterIcon.js
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/FooterIcon.scss
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/Icons/FacebookIcon.js
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/Icons/FacebookIcon.scss
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/Icons/InstagramIcon.js
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/Icons/InstagramIcon.scss
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/Icons/MobileIcon.js
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/Icons/MobileIcon.scss
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/Icons/NaverIcon.js
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/Icons/NaverIcon.scss
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/Icons/YoutubeIcon.js
  src/Pages/MyPage/Components/MyPageFooter/FooterIcon/Icons/YoutubeIcon.scss
  src/Pages/MyPage/Components/MyPageFooter/KakaoBtn/KakaoBtn.js
  src/Pages/MyPage/Components/MyPageFooter/KakaoBtn/KakaoBtn.scss
  src/Pages/MyPage/Components/MyPageFooter/MyPageFooter.js
  src/Pages/MyPage/Components/MyPageFooter/MyPageFooter.scss
  src/Pages/MyPage/Components/MyPageNav/MyPageNav.js
  src/Pages/MyPage/Components/MyPageNav/MyPageNav.scss
  src/Pages/MyPage/MyPage.js
  src/Routes.js
  src/Styles/styled.js
Labels: Status: 리뷰 요청

#11 [배정규] Add: 찜하기 기능 개선
  .eslintrc.json
  public/data/MyPageData.json
  public/images/membership 2.png
  public/images/profileImg 2.png
  public/index.html
  src/Components/Signature/Main/ClassCardList/ClassCardList.js
  src/Components/Signature/Main/ClassCardList/OpenSignatureClass/OpenSignatureClass.js
  src/Components/Signature/Main/ClassCardList/OpenSignatureClass/OpenSignatureClass.scss
  src/Config.js
  src/Pages/MyPage/Components/Content/MyViewClassList/MyViewClassList.js
  src/Pages/MyPage/Components/Content/MyViewClassList/ViewClass.js
  src/Pages/MyPage/Components/Content/MyViewClassList/ViewClass.scss
  src/Pages/MyPage/Components/Content/WishClassList/WishClass.js
  src/Pages/MyPage/Components/Content/WishClassList/WishClass.scss
  src/Pages/MyPage/Components/Content/WishClassList/WishClassList.js
  src/Pages/MyPage/Components/LeftAside/ProfileCard/ProfileCard.js
  src/Pages/MyPage/Components/LeftAside/ProfileCard/Wish.js
  src/Pages/MyPage/Components/MyPageNav/MyPageNav.js
  src/Pages/MyPage/MyPage.js
  src/Pages/Signature/Detail/Recommend.js
Labels: Status: 리뷰 요청

#5 [배정규] Add: 시그니처 디테일 페이지 모달 기능 구현
  public/data/signatureProduct.json
  public/images/datail1.webp
  public/images/datail2.webp
  public/images/datail3.webp
  public/images/datail4.webp
  public/images/detailTopImg.webp
  src/Config.js
  src/Pages/Signature/Detail/Modal.js
  src/Pages/Signature/Detail/SignatureHeadCover.js
  src/Routes.js
Labels: Status: Accepted

#14 [신영재] Add: 스트리밍 페이지 댓글 기능 완성
  package-lock.json
  package.json
  public/data/MyPageData.json
  public/data/classData.json
  public/index.html
  src/Config.js
  src/Pages/Login/LoginInput.js
  src/Pages/Signature/Detail/Comment.js
  src/Pages/Streaming/Streaming.js
Labels: Status: 리뷰 요청

#12 [배정규] Add: 마이페이지 유저정보 가져오기 구현
  src/Config.js
  src/Pages/MyPage/Components/LeftAside/ProfileCard/ProfileCard.js
  src/Pages/MyPage/Components/LeftAside/ProfileCard/ProfileEdit.js
  src/Pages/MyPage/Components/MyPageNav/MyPageNav.scss
  src/Pages/MyPage/MyPage.js
  src/Pages/SignUp/SocialLogin.js
Labels: Status: 리뷰 요청

#17 [신영재] Fix: API 주소 수정
  src/Components/Signature/Main/ClassCardList/ClassCardList.js
  src/Components/SignatureSideBar/Components/SummaryOptions.js
  src/Components/SignatureSideBar/SignatureSideBar.js
  src/Config.js
  src/Pages/Login/LoginInput.js
  src/Pages/Login/LoginTitle.js
  src/Pages/Signature/Detail/ClassSummary.js
  src/Pages/Signature/Detail/DetailPage.js
  src/Pages/Signature/Detail/Recommend.js
  src/Pages/Signature/Detail/SignatureHeadCover.js
  src/Pages/Signature/Detail/SimilarClass.js
  src/Routes.js
Labels: Status: 리뷰 요청

#13 [배정규] Add: 시그니처 디테일 사이드바 sticky 구현
  src/Components/SignatureSideBar/SignatureSideBar.js
  src/Config.js
  src/Pages/Signature/Detail/DetailPage.js
  src/Pages/Signature/Detail/SignatureHeadCover.js
Labels: Status: Accepted

#18 [신영재] Fix: API 주소 수정
  src/Config.js
Labels: Status: 리뷰 요청

#20 [신영재] Fix: 오류 해결
  src/Components/SignatureSideBar/SignatureSideBar.js
  src/Config.js
  src/Pages/MyPage/Components/Content/MyViewClassList/ViewClass.js
  src/Pages/MyPage/Components/Content/WishClassList/WishClass.js
  src/Pages/Signature/Detail/DetailPage.js
  src/Pages/Signature/Detail/Recommend.js
  src/Pages/Signature/Detail/SignatureHeadCover.js
Labels: Status: Accepted

#21 Fix: 오류 해결
  src/Components/SignatureSideBar/SignatureSideBar.js
  src/Config.js
  src/Pages/MyPage/Components/Content/MyViewClassList/ViewClass.js
  src/Pages/MyPage/Components/Content/WishClassList/WishClass.js
  src/Pages/Signature/Detail/DetailPage.js
  src/Pages/Signature/Detail/Recommend.js
  src/Pages/Signature/Detail/SignatureHeadCover.js
Labels: Status: 리뷰 요청

#16 [배정규] Modify: 시그니처 모달 기능 개선
  src/Pages/Signature/Detail/DetailPage.js
  src/Pages/Signature/Detail/Modal.js
  src/Pages/Signature/Detail/SignatureHeadCover.js
Labels: Status: 리뷰 요청

#15 [배정규] Fix: rebase 충돌 해결
  src/Components/SignatureSideBar/Components/ProductPriceInfo.js
Labels: Status: 리뷰 요청

#23 [배정규] Add: 유저 토큰 관리 및 찜하기, 마이페이지 개선
  src/Components/Signature/Main/ClassCardList/OpenSignatureClass/OpenSignatureClass.js
  src/Config.js
  src/Pages/MyPage/Components/Content/MyViewClassList/MyViewClassList.js
  src/Pages/MyPage/Components/Content/MyViewClassList/ViewClass.js
  src/Pages/MyPage/Components/Content/WishClassList/WishClass.js
  src/Pages/MyPage/MyPage.js
  src/Pages/SignUp/SocialLogin.js
  src/Pages/Signature/Detail/DetailPage.js
Labels: Status: 리뷰 요청

#24 [신영재] Add: 최종 수정
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/FooterIcon/Icons/NaverIcon.js
  src/Components/Footer/KakaoBtn/KakaoBtn.js
  src/Components/Footer/KakaoBtn/KakaoBtn.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/NavHeader.js
  src/Components/Nav/NavLogo/NavLogo.js
  src/Components/Nav/NavRight.js
  src/Components/Nav/NavRight.scss
  src/Components/Signature/Main/ClassAbout/ClassAbout.js
  src/Components/Signature/Main/ClassCardList/ClassCardList.js
  src/Components/Signature/Main/ClassCardList/OpenSignatureClass/OpenSignatureClass.js
  src/Components/Signature/Main/ClassCardList/OpenSignatureClass/OpenSignatureClass.scss
  src/Components/Signature/Main/TitleSlide/TitleSlide.js
  src/Components/SignatureSideBar/Components/WishShare.js
  src/Config.js
  src/Pages/Login/LoginInput.js
  src/Pages/MyPage/Components/Content/MyViewClassList/MyViewClassList.js
  src/Pages/MyPage/Components/Content/MyViewClassList/ViewClass.js
  src/Pages/MyPage/Components/Content/MyViewClassList/ViewClass.scss
  src/Pages/MyPage/Components/Content/WishClassList/WishClass.js
  src/Pages/MyPage/Components/Content/WishClassList/WishClass.scss
  src/Pages/MyPage/Components/Content/WishClassList/WishClassList.js
  src/Pages/MyPage/Components/LeftAside/ProfileCard/Wish.js
  src/Pages/MyPage/MyPage.js
  src/Pages/Signature/Detail/DetailPage.js
  src/Pages/Signature/Detail/Modal.js
  src/Pages/Signature/Main/Main.js
  src/Pages/Streaming/Streaming.js
  src/Styles/styled.js
Labels: Status: 리뷰 요청
